BEGIN;
CREATE TYPE "Role_new" AS ENUM ('ADMIN', 'EXECUTIVE', 'SALES_MANAGER', 'ACCOUNT_EXECUTIVE');
ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "users" ALTER COLUMN "role" TYPE "Role_new" USING ("role"::text::"Role_new");
ALTER TYPE "Role" RENAME TO "Role_old";
ALTER TYPE "Role_new" RENAME TO "Role";
DROP TYPE "Role_old";
ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'ACCOUNT_EXECUTIVE';
COMMIT;
